# Welcome to Jekyll!
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Eli Mattingly's GitHub Site
email: ematting@mit.edu
description: >- # this means to ignore newlines until "baseurl:"
  A site that hosts the projects which I have worked on, Art, Engineering, or otherwise
github_username: EliMattingly22
minimal_mistakes_skin: default
search: true
# Build settings

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
include:
  - _pages
  - _posts
  - _projects
  - _art
  - _research
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - _ignore
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby
# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


author:

  name   : "Eli Mattingly"

  avatar : "/assets/images/Headshot_Square2.jpg"

  bio    : " "

  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/OS-MPI"
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/OS-MPI"

    
defaults:
  # _pages
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      comments: true
      share: true
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: single
      author_profile: true
      comments: true
      share: true
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
collections:
  projects:
    output: true
    permalink: /:collection/:path/
  art:
    output: true
    permalink: /:collection/:path/
  research:
    output: true
    permalink: /:collection/:path/
